{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-09T18:59:25.620Z"}
