{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:04.830Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:05.137Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:07.559Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:13.989Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:16.191Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:18.099Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:19.061Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:19.355Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:19.823Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:20.411Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:21.995Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:23.145Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:24.166Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:24.204Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:24.307Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:25.391Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:26.880Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:00:42.609Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:02:08.017Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:04:24.451Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:07:30.259Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:11:07.652Z"}
